# Generated by Django 5.0.1 on 2024-01-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_description_alter_product_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="promotion",
            field=models.ManyToManyField(blank=True, to="store.promotion"),
        ),
    ]
